### ISSUE TITLE
Getting 'Page matching query does not exist' error when trying to add a new Page

### ISSUE THREAD

**Issue by rosco77** [ababic/wagtailmodeladmin#10]
When trying to add a new Page via wagtailmodeladmin I receive the 'Page matching query does not exist'.
[screen shot 2015-08-26 at 15 05 24](https://cloud.githubusercontent.com/assets/592713/9495661/993b5878-4c04-11e5-857c-2463444f171a.png)
[screen shot 2015-08-26 at 15 05 45](https://cloud.githubusercontent.com/assets/592713/9495664/9b80485a-4c04-11e5-8004-55d49ccda75e.png)

models.py file

```
from django.db import models

from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel


class PortfolioPage(Page):
    body = RichTextField(blank=True)
    date = models.DateField("Launch date")
    background = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
        FieldPanel('date'),
        ImageChooserPanel('background'),
    ]

@register_snippet
class Portfolio(models.Model):
    intro = models.CharField(max_length=255)
    published = models.BooleanField(default=True)

    panels = [
        FieldPanel('published'),
        FieldPanel('intro'),
    ]

    def __str__(self):
        return self.intro
```

wagtail_hooks.py

```
from wagtail.wagtailcore import hooks
from wagtailmodeladmin.options import ModelAdmin, ModelAdminGroup, PageModelAdmin
from .models import Portfolio, PortfolioPage


class PortfolioPageAdmin(ModelAdmin):
    model = PortfolioPage
    menu_label = 'Case Study Page' # ditch this to use verbose_name_plural from model
    menu_icon = 'date' # change as required
    menu_order = 200 # will put in 3rd place (000 being 1st, 100 2nd)


class PortfolioAdmin(ModelAdmin):
    model = Portfolio
    menu_label = 'Case Study Snippet' # ditch this to use verbose_name_plural from model
    menu_icon = 'date' # change as required
    menu_order = 100 # will put in 3rd place (000 being 1st, 100 2nd)
    list_display = ('published', 'intro',)
    list_filter = ('published',)
    search_fields = ('intro',)


class PortfolioAdminGroup(ModelAdminGroup):
    menu_label = 'Portfolio'
    menu_icon = 'folder-open-inverse' # change as required
    menu_order = 000 # will put in 3rd place (000 being 1st, 100 2nd)
    items = (PortfolioPageAdmin, PortfolioAdmin)


hook_instance = PortfolioAdminGroup()

@hooks.register('register_permissions')
def register_permissions():
    return hook_instance.get_permissions_for_registration()


@hooks.register('register_admin_urls')
def register_admin_urls():
    return hook_instance.get_admin_urls_for_registration()


@hooks.register('register_admin_menu_item')
def register_admin_menu_item():
    return hook_instance.get_menu_item()
```

**Comment by ababic** [comment]
Hi @rosco77! Can I just check whether you have a root page set for your site, and that your pages are children of that page?

**Comment by rosco77** [comment]
Hi @ababic I've actually just destroyed the site I was using and have gone back to vanilla Wagtail so can't fully check.  On my site I had a HomePage that inherited from Page.  This was shown on the Root page of the Wagtail Admin.

The single page you see in the list is the child page that was created under the HomePage using the standard Wagtail Admin.  

When I tried to create a page via the wagtailmodeladmin group that's when it gave the error.  I'm not sure how I would configure that to specify it was a child of another page.  

Apologies if I'm missing something.  I only started going through Wagtail as a CMS yesterday and the documentation seems to be a bit sparse in places.

**Comment by ababic** [comment]
@rosco77 I've pushed an update that I'm fairly sure should fix the error you were having. If you have any luck replicating things again in order to test, please let me know :)

**Comment by rosco77** [comment]
Thanks @ababic will test again now and feedback.

**Comment by rosco77** [comment]
It's working now.  Many thanks for the quick fix.  Great app BTW.

**Comment by ababic** [comment]
No problem. I'm glad you're finding it useful!
