### ISSUE TITLE
Multiple `ModelAdmin`s, but without `ModelAdminGroup`

### ISSUE THREAD

**Issue by tombreit** [ababic/wagtailmodeladmin#14]
How can I hook more than one `ModelAdmin`s  in my Wagtail-admin without grouping them via `ModelAdminGroup`?
Like in your [simple example](https://github.com/ababic/wagtailmodeladmin#a-simple-example) - but with `MyPageModelAdmin`, `MySecondPageModelAdmin` and so on?

**Comment by ababic** [comment]
Hi @tombreit,

I've not actully done this yet, but I think repeating the hook_instance instantiation and hook method parts should do the trick. You'll just need to rename things slightly each time to avoid things being overridden. e.g:

    hook_instance1 = MyPageModelAdmin()

    @hooks.register('register_permissions')
    def register_permissions1():
        return hook_instance1.get_permissions_for_registration()


    @hooks.register('register_admin_urls')
    def register_admin_urls1():
        return hook_instance1.get_admin_urls_for_registration()


    @hooks.register('register_admin_menu_item')
    def register_admin_menu_item1():
        return hook_instance1.get_menu_item()

    hook_instance2 = MySecondPageModelAdmin()

    @hooks.register('register_permissions')
    def register_permissions2():
        return hook_instance2.get_permissions_for_registration()


    @hooks.register('register_admin_urls')
    def register_admin_urls2():
        return hook_instance2.get_admin_urls_for_registration()


    @hooks.register('register_admin_menu_item')
    def register_admin_menu_item2():
        return hook_instance2.get_menu_item()

**Comment by tombreit** [comment]
Thanks for this hint (I'll try it), but perhaps I should - in order to minimize duplicate code - use "your way" aka `ModelAdminGroup`.

**Comment by johnfraney** [comment]
@tombreit This code mirrors Django's `admin.site.register` workflow, and it has been working well for me (you can move the `wagtail_modeladmin_register` function elsewhere for reusability):

```
from wagtail.wagtailcore import hooks
from wagtailmodeladmin.options import ModelAdmin as WagtailModelAdmin

from .models import Chocolate, Banana


class BananaModelAdmin(WagtailModelAdmin):
    model = Banana
    menu_icon = 'user'
    menu_order = 200
    ...


class ChocolateModelAdmin(WagtailModelAdmin):
    model = Chocolate
    menu_icon = 'list-ol'
    menu_order = 200
    ...


def wagtail_modeladmin_register(wagtailmodeladmin_model):
    """Registers the Model in Wagtail's left menu"""
    wagtailmodeladmin_instance = wagtailmodeladmin_model()

    @hooks.register('register_permissions')
    def register_permissions():
        return wagtailmodeladmin_instance.get_permissions_for_registration()

    @hooks.register('register_admin_urls')
    def register_admin_urls():
        return wagtailmodeladmin_instance.get_admin_urls_for_registration()

    @hooks.register('register_admin_menu_item')
    def register_admin_menu_item():
        return wagtailmodeladmin_instance.get_menu_item()


wagtail_modeladmin_register(BananaModelAdmin)
wagtail_modeladmin_register(ChocolateModelAdmin)
```

**Comment by ababic** [comment]
@johnfraney Really nice implementation. Do you mind if I steal your good work and add something similar into the project?

**Comment by johnfraney** [comment]
@ababic Thanks! I don't mind at all if you use this. I've been meaning to send a PR but haven't had time.

**Comment by ababic** [comment]
@tombreit If you pull the latest version, you should be able to import wagtailmodeladmin_register from wagtailmodeladmin.options, and use that :)
