### ISSUE TITLE
Getting a UnicodeEncodeError when using unicode characters in a field value

### ISSUE THREAD

**Issue by saevarom** [ababic/wagtailmodeladmin#15]
When a field that is listed in list_display for the modeladmin has a unicode value, I get an error.

UnicodeEncodeError at /admin/modeladmin/feeds/feed/
'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

/Users/123/Virtualenvs/xyz/lib/python2.7/site-packages/wagtailmodeladmin/templatetags/wagtailmodeladmin_tags.py in items_for_result in line 63

**Comment by ababic** [comment]
Hi @saevarom I have pushed a fix that seemed to solve the problem locally. Would you be able to check if it works for you?

**Comment by saevarom** [comment]
Yep, that's it, works great!
Thanks,
