### ISSUE TITLE
Any plans to put this repo on PyPi?

### ISSUE THREAD

**Issue by seddonym** [ababic/wagtailmodeladmin#18]
It would be great if it was possible to install via:

    pip install wagtailmodeladmin

**Comment by ababic** [comment]
I agree, that would be benefitial, and something I'd like to happen. I just haven't done it before, so wasn't sure what the process was. I'm hoping i'll have time to look into it and sort.

It might be worth mentioning that this package is currently under review for inclusion into wagtail itself (in some form or other) in version 1.2 (https://github.com/torchbox/wagtail/issues/1657). So, you might not need to have it as a dependency at all in the near future.

**Comment by seddonym** [comment]
Hi!

Good news about inclusion in wagtail core.

It's really simple to add to pypi, since you've already got your setup.py.  I think it's just a couple of commands.  See this post: http://peterdowns.com/posts/first-time-with-pypi.html

Scroll down to near the bottom: `python setup.py register -r pypitest `.  It's been a while since I did it but think it's just that commands and the ones after it.

Hope helps!

**Comment by SalahAdDin** [comment]
:+1: Please, PyPi!

**Comment by ababic** [comment]
Thanks for the link @seddonym. Work is a little manic at the moment, but I'll add this to my to-do list for when things calm down.

**Comment by seddonym** [comment]
Hi Andy,

I hope you don't mind, but I have now pushed this to Pypi as I needed it for a deployment.

I can transfer ownership of the repo over to you if you let me know your Pypi account.

In the meantime, wagtailmodeladmin can now be installed via `pip install wagtailmodeladmin`.

Incidentally, all I needed to do was:

    git clone git@github.com:ababic/wagtailmodeladmin.git
    python setup.py register
    python setup.py sdist upload

Then if you make any changes, you just bump the version number up and then run:

    python setup.py sdist upload

Let me know if you need any help, and I hope you don't mind me pushing it forward.

**Comment by ababic** [comment]
Hi @seddonym No problem at all. I was always for the idea, and even laid some initial groundwork, but have just been too distracted with other things lately. 

I don't have a Pypi account, but will set one up soon and get back to you regarding the transfer. I don't even mind it being in your account... just might be a little inconvenient when it comes to getting new changes out.

**Comment by seddonym** [comment]
No problem - just let me know and I'll make you the owner.  Thanks again!

Perhaps we can close this ticket?

**Comment by ababic** [comment]
Hi @seddonym. Could you transfer it over to ababic when you get chance? Thanks.

**Comment by seddonym** [comment]
Done.  Let me know if any questions.
