### ISSUE TITLE
module urlparse not found

### ISSUE THREAD

**Issue by tombreit** [ababic/wagtailmodeladmin#2]
Running with python3.4 I get `ImportError: No module named 'urlparse'`

After replacing 

    from urlparse import urlparse

with 

    from urllib.parse import urlparse

in 

    wagtailmodeladmin/middleware.py

this seems to be fixed.

**Comment by ababic** [comment]
Good find @tombreit! we haven't tried it in python 3.4, so I'm relieved to hear that's the only incompatibility you've found. we should be able to import via six to support both.
