### ISSUE TITLE
MANIFEST.in missing from 2.0.4 package on

### ISSUE THREAD

**Issue by nicklo** [ababic/wagtailmodeladmin#24]
packages > 2.0.3 do not appear to have a MANIFEST.in file so wagtailmodeladmin fails to properly install  via pip.

**Comment by ababic** [comment]
Sorry! When packaging for pip, it created a new MANIFEST file, which I'd never seen before, and so didn't add into the repo. The latest version should install fine now.

**Comment by nicklo** [comment]
Many thanks Andy and no need for "Sorry!". We all owe you, not the other way around.
