### ISSUE TITLE
error in get_search_results - reduce(). removed from python 3

### ISSUE THREAD

**Issue by tombreit** [ababic/wagtailmodeladmin#3]
Hi, 
the search function in wagtailmodeladmin seems to rely on `reduce()`, which was removed in python 3.  Any chance you find a way to implement this functionality without `reduce`?

Occurred in: 

    wagtailmodeladmin/options.py in get_search_results
    Line 148  queryset = queryset.filter(reduce(operator.or_, or_queries))

     

Reference: 
> https://docs.python.org/3.0/whatsnew/3.0.html#builtins: 
> Removed <tt class="xref docutils literal"><span class="pre">reduce()</span></tt>.  Use <a title="functools.reduce" class="reference external" href="../library/functools.html#functools.reduce"><tt class="xref docutils literal"><span class="pre">functools.reduce()</span></tt></a> if you really
need it; however, 99 percent of the time an explicit <a class="reference external" href="../reference/compound_stmts.html#for"><tt class="xref docutils literal"><span class="pre">for</span></tt></a>
loop is more readable.

**Comment by ababic** [comment]
@tombreit. It looks as though Django contributors thought it best to import reduce from functools to get around the exact same issue in ModelAdmin (https://github.com/django/django/blob/master/django/contrib/admin/options.py) so I'm going to go ahead with that approach. 

Will push a fix very soon. Thanks again for your input!

**Comment by tombreit** [comment]
Thanks a lot for your work! I'm quite new to python, django and wagtail and appreciate your prompt help.
